baseURL = "/"
relativeURLs = true
canonifyURLs = false
languageCode = "en-us"
title = "AI SMB SecOps Books, Blogs, and Resources"
theme = "PaperMod"
[params]
  description = "A practical guide to AIâ€‘Sec"
  author = "delphijc"
  showReadingTime = true
  disableSpecial1 = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 20
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40
